# WARNING: you must put this file in 
# app/config/security.yml
security:
    encoders:
        Samples\BlogBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers: 
        user_db:
            entity: { class: Samples\BlogBundle\Entity\User, property: username }

    firewalls:
#        login_area:
#            pattern: ^/blog/login
#            anonymous: ~
        secured_area:
            pattern: ^/
            provider: user_db
            anonymous: ~
            logout:
                path: /logout
                target: /blog/login
            form_login: 
                login_path: /blog/login
                check_path: /login_check

    access_control: 
       - { path: ^/blog/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/blog/*, roles: ROLE_USER }