Pello\CustomerCrudBundle\Entity\Customer:
    getters:
        name:
            - NotBlank: {'message' : 'Put your name or something'}
            - Length: { 'min' : 3, 'minMessage' : '3 chars at least'}
        description:
            - NotBlank: ~